<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseLocalProjectReference>false</UseLocalProjectReference>    
    
    <TargetFramework>net9.0</TargetFramework>
    <UseMaui>true</UseMaui>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <!-- NuGet Package -->
  <PropertyGroup>
    <Description>Declarative UIs for .NET MAUI with F# and MVU, using Fabulous</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
  <!-- SourceLink -->
  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
  <PropertyGroup Condition="$(GITHUB_ACTIONS) == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\logo\nuget-icon.png" Pack="true" PackagePath="\" />
    <Compile Include="ViewNode.fs" />
    <Compile Include="Attributes.fs" />
    <Compile Include="VirtualizedCollection.fs" />
    <Compile Include="Widgets.fs" />
    <Compile Include="Views\_Element\Element.fs" />
    <Compile Include="Views\_Element\Element.Mvu.fs" />
    <Compile Include="Views\_Geometry.fs" />
    <Compile Include="Views\_NavigableElement.fs" />
    <Compile Include="Views\Shadow.fs" />
    <Compile Include="Views\Brushes\_Brush.fs" />
    <Compile Include="Views\Brushes\GradientStop.fs" />
    <Compile Include="Views\Brushes\_GradientBrush.fs" />
    <Compile Include="Views\Brushes\SolidColorBrush.fs" />
    <Compile Include="Views\Brushes\LinearGradientBrush.fs" />
    <Compile Include="Views\Brushes\RadialGradientBrush.fs" />
    <Compile Include="Views\_VisualElement\VisualElement.fs" />
    <Compile Include="Views\_VisualElement\VisualElement.Component.fs" />
    <Compile Include="Views\_VisualElement\VisualElement.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\_GestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\DragGestureRecognizer\DragGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\DragGestureRecognizer\DragGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\DragGestureRecognizer\DragGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\DropGestureRecognizer\DropGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\DropGestureRecognizer\DropGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\DropGestureRecognizer\DropGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\PanGestureRecognizer\PanGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\PanGestureRecognizer\PanGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\PanGestureRecognizer\PanGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\PinchGestureRecognizer\PinchGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\PinchGestureRecognizer\PinchGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\PinchGestureRecognizer\PinchGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\SwipeGestureRecognizer\SwipeGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\SwipeGestureRecognizer\SwipeGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\SwipeGestureRecognizer\SwipeGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\TapGestureRecognizer\TapGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\TapGestureRecognizer\TapGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\TapGestureRecognizer\TapGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\GestureRecognizers\PointerGestureRecognizer\PointerGestureRecognizer.fs" />
    <Compile Include="Views\GestureRecognizers\PointerGestureRecognizer\PointerGestureRecognizer.Component.fs" />
    <Compile Include="Views\GestureRecognizers\PointerGestureRecognizer\PointerGestureRecognizer.Mvu.fs" />
    <Compile Include="Views\_View.fs" />
    <Compile Include="Views\KeyboardAccelerator.fs" />
    <Compile Include="Views\MenuItems\MenuItem\MenuItem.fs" />
    <Compile Include="Views\MenuItems\MenuItem\MenuItem.Component.fs" />
    <Compile Include="Views\MenuItems\MenuItem\MenuItem.Mvu.fs" />
    <Compile Include="Views\MenuItems\ToolbarItem\ToolbarItem.fs" />
    <Compile Include="Views\MenuItems\ToolbarItem\ToolbarItem.Component.fs" />
    <Compile Include="Views\MenuItems\ToolbarItem\ToolbarItem.Mvu.fs" />
    <Compile Include="Views\MenuItems\MenuFlyoutItem\MenuFlyoutItem.fs" />
    <Compile Include="Views\MenuItems\MenuFlyoutItem\MenuFlyoutItem.Component.fs" />
    <Compile Include="Views\MenuItems\MenuFlyoutItem\MenuFlyoutItem.Mvu.fs" />
    <Compile Include="Views\Cells\_Cell\Cell.fs" />
    <Compile Include="Views\Cells\_Cell\Cell.Component.fs" />
    <Compile Include="Views\Cells\_Cell\Cell.Mvu.fs" />
    <Compile Include="Views\Cells\ViewCell.fs" />
    <Compile Include="Views\Cells\TextCell.fs" />
    <Compile Include="Views\Cells\ImageCell.fs" />
    <Compile Include="Views\Cells\SwitchCell\SwitchCell.fs" />
    <Compile Include="Views\Cells\SwitchCell\SwitchCell.Component.fs" />
    <Compile Include="Views\Cells\SwitchCell\SwitchCell.Mvu.fs" />
    <Compile Include="Views\Cells\EntryCell\EntryCell.fs" />
    <Compile Include="Views\Cells\EntryCell\EntryCell.Component.fs" />
    <Compile Include="Views\Cells\EntryCell\EntryCell.Mvu.fs" />
    <Compile Include="Views\Pages\_Page\Page.fs" />
    <Compile Include="Views\Pages\_Page\Page.Component.fs" />
    <Compile Include="Views\Pages\_Page\Page.Mvu.fs" />
    <Compile Include="Views\Pages\_MultiPageOfPage\MultiPageOfPage.fs" />
    <Compile Include="Views\Pages\_MultiPageOfPage\MultiPageOfPage.Component.fs" />
    <Compile Include="Views\Pages\_MultiPageOfPage\MultiPageOfPage.Mvu.fs" />
    <Compile Include="Views\Pages\ContentPage\ContentPage.fs" />
    <Compile Include="Views\Pages\ContentPage\ContentPage.Component.fs" />
    <Compile Include="Views\Pages\ContentPage\ContentPage.Mvu.fs" />
    <Compile Include="Views\Pages\FlyoutPage\FlyoutPage.fs" />
    <Compile Include="Views\Pages\FlyoutPage\FlyoutPage.Component.fs" />
    <Compile Include="Views\Pages\FlyoutPage\FlyoutPage.Mvu.fs" />
    <Compile Include="Views\Pages\TabbedPage.fs" />
    <Compile Include="Views\Pages\NavigationPage\NavigationPage.fs" />
    <Compile Include="Views\Pages\NavigationPage\NavigationPage.Component.fs" />
    <Compile Include="Views\Pages\NavigationPage\NavigationPage.Mvu.fs" />
    <Compile Include="Views\Shapes\Segments\_PathSegment.fs" />
    <Compile Include="Views\Shapes\Segments\PathFigure.fs" />
    <Compile Include="Views\Shapes\Segments\ArcSegment.fs" />
    <Compile Include="Views\Shapes\Segments\BezierSegment.fs" />
    <Compile Include="Views\Shapes\Segments\LineSegment.fs" />
    <Compile Include="Views\Shapes\Segments\PolyBezierSegment.fs" />
    <Compile Include="Views\Shapes\Segments\PolyLineSegment.fs" />
    <Compile Include="Views\Shapes\Segments\PolyQuadraticBezierSegment.fs" />
    <Compile Include="Views\Shapes\Segments\QuadraticBezierSegment.fs" />
    <Compile Include="Views\Shapes\Geometries\EllipseGeometry.fs" />
    <Compile Include="Views\Shapes\Geometries\LineGeometry.fs" />
    <Compile Include="Views\Shapes\Geometries\RectangleGeometry.fs" />
    <Compile Include="Views\Shapes\Geometries\PathGeometry.fs" />
    <Compile Include="Views\Shapes\Geometries\GeometryGroup.fs" />
    <Compile Include="Views\Shapes\Geometries\RoundRectangleGeometry.fs" />
    <Compile Include="Views\Shapes\PathTransforms\_Transform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\RotateTransform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\ScaleTransform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\SkewTransform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\TranslateTransform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\CompositeTransform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\MatrixTransform.fs" />
    <Compile Include="Views\Shapes\PathTransforms\TransformGroup.fs" />
    <Compile Include="Views\Shapes\_Shape.fs" />
    <Compile Include="Views\Shapes\Ellipse.fs" />
    <Compile Include="Views\Shapes\Rectangle.fs" />
    <Compile Include="Views\Shapes\RoundRectangle.fs" />
    <Compile Include="Views\Shapes\Path.fs" />
    <Compile Include="Views\Shapes\Line.fs" />
    <Compile Include="Views\Shapes\Polygon.fs" />
    <Compile Include="Views\Shapes\Polyline.fs" />
    <Compile Include="Views\Layouts\_Layout.fs" />
    <Compile Include="Views\Layouts\_TemplatedView.fs" />
    <Compile Include="Views\Layouts\ContentView.fs" />
    <Compile Include="Views\Layouts\RefreshView\RefreshView.fs" />
    <Compile Include="Views\Layouts\RefreshView\RefreshView.Component.fs" />
    <Compile Include="Views\Layouts\RefreshView\RefreshView.Mvu.fs" />
    <Compile Include="Views\Layouts\_LayoutOfView.fs" />
    <Compile Include="Views\Layouts\_StackBase.fs" />
    <Compile Include="Views\Layouts\VerticalStackLayout.fs" />
    <Compile Include="Views\Layouts\HorizontalStackLayout.fs" />
    <Compile Include="Views\Layouts\ZStack.fs" />
    <Compile Include="Views\Layouts\Grid.fs" />
    <Compile Include="Views\Layouts\ScrollView\ScrollView.fs" />
    <Compile Include="Views\Layouts\ScrollView\ScrollView.Component.fs" />
    <Compile Include="Views\Layouts\ScrollView\ScrollView.Mvu.fs" />
    <Compile Include="Views\Layouts\Border.fs" />
    <Compile Include="Views\Layouts\AbsoluteLayout.fs" />
    <Compile Include="Views\Layouts\FlexLayout.fs" />
    <Compile Include="Views\Layouts\SwipeItem\SwipeItem.fs" />
    <Compile Include="Views\Layouts\SwipeItem\SwipeItem.Component.fs" />
    <Compile Include="Views\Layouts\SwipeItem\SwipeItem.Mvu.fs" />
    <Compile Include="Views\Layouts\SwipeItems.fs" />
    <Compile Include="Views\Layouts\SwipeView\SwipeView.fs" />
    <Compile Include="Views\Layouts\SwipeView\SwipeView.Component.fs" />
    <Compile Include="Views\Layouts\SwipeView\SwipeView.Mvu.fs" />
    <Compile Include="Views\Layouts\TitleBar.fs" />
    <Compile Include="Views\Controls\IndicatorView.fs" />
    <Compile Include="Views\Controls\Label.fs" />
    <Compile Include="Views\Controls\Span.fs" />
    <Compile Include="Views\Controls\FormattedLabel.fs" />
    <Compile Include="Views\Controls\Button\Button.fs" />
    <Compile Include="Views\Controls\Button\Button.Component.fs" />
    <Compile Include="Views\Controls\Button\Button.Mvu.fs" />
    <Compile Include="Views\Controls\Switch\Switch.fs" />
    <Compile Include="Views\Controls\Switch\Switch.Component.fs" />
    <Compile Include="Views\Controls\Switch\Switch.Mvu.fs" />
    <Compile Include="Views\Controls\Slider\Slider.fs" />
    <Compile Include="Views\Controls\Slider\Slider.Component.fs" />
    <Compile Include="Views\Controls\Slider\Slider.Mvu.fs" />
    <Compile Include="Views\Controls\ActivityIndicator.fs" />
    <Compile Include="Views\Controls\Image.fs" />
    <Compile Include="Views\Controls\BoxView.fs" />
    <Compile Include="Views\Controls\_InputView\InputView.fs" />
    <Compile Include="Views\Controls\_InputView\InputView.Component.fs" />
    <Compile Include="Views\Controls\_InputView\InputView.Mvu.fs" />
    <Compile Include="Views\Controls\Entry\Entry.fs" />
    <Compile Include="Views\Controls\Entry\Entry.Component.fs" />
    <Compile Include="Views\Controls\Entry\Entry.Mvu.fs" />
    <Compile Include="Views\Controls\SearchBar\SearchBar.fs" />
    <Compile Include="Views\Controls\SearchBar\SearchBar.Component.fs" />
    <Compile Include="Views\Controls\SearchBar\SearchBar.Mvu.fs" />
    <Compile Include="Views\Controls\Editor\Editor.fs" />
    <Compile Include="Views\Controls\Editor\Editor.Component.fs" />
    <Compile Include="Views\Controls\Editor\Editor.Mvu.fs" />
    <Compile Include="Views\Controls\ImageButton\ImageButton.fs" />
    <Compile Include="Views\Controls\ImageButton\ImageButton.Component.fs" />
    <Compile Include="Views\Controls\ImageButton\ImageButton.Mvu.fs" />
    <Compile Include="Views\Controls\DatePicker\DatePicker.fs" />
    <Compile Include="Views\Controls\DatePicker\DatePicker.Component.fs" />
    <Compile Include="Views\Controls\DatePicker\DatePicker.Mvu.fs" />
    <Compile Include="Views\Controls\Picker\Picker.fs" />
    <Compile Include="Views\Controls\Picker\Picker.Component.fs" />
    <Compile Include="Views\Controls\Picker\Picker.Mvu.fs" />
    <Compile Include="Views\Controls\TimePicker\TimePicker.fs" />
    <Compile Include="Views\Controls\TimePicker\TimePicker.Component.fs" />
    <Compile Include="Views\Controls\TimePicker\TimePicker.Mvu.fs" />
    <Compile Include="Views\Controls\Stepper\Stepper.fs" />
    <Compile Include="Views\Controls\Stepper\Stepper.Component.fs" />
    <Compile Include="Views\Controls\Stepper\Stepper.Mvu.fs" />
    <Compile Include="Views\Controls\WebView\WebView.fs" />
    <Compile Include="Views\Controls\WebView\WebView.Component.fs" />
    <Compile Include="Views\Controls\WebView\WebView.Mvu.fs" />
    <Compile Include="Views\Controls\CheckBox\CheckBox.fs" />
    <Compile Include="Views\Controls\CheckBox\CheckBox.Component.fs" />
    <Compile Include="Views\Controls\CheckBox\CheckBox.Mvu.fs" />
    <Compile Include="Views\Controls\ProgressBar.fs" />
    <Compile Include="Views\Controls\RadioButton\RadioButton.fs" />
    <Compile Include="Views\Controls\RadioButton\RadioButton.Component.fs" />
    <Compile Include="Views\Controls\RadioButton\RadioButton.Mvu.fs" />
    <Compile Include="Views\Controls\GraphicsView\GraphicsView.fs" />
    <Compile Include="Views\Controls\GraphicsView\GraphicsView.Component.fs" />
    <Compile Include="Views\Controls\GraphicsView\GraphicsView.Mvu.fs" />
    <Compile Include="Views\Controls\HybridWebView\HybridWebView.fs" />
    <Compile Include="Views\Controls\HybridWebView\HybridWebView.Component.fs" />
    <Compile Include="Views\Controls\HybridWebView\HybridWebView.Mvu.fs" />
    <Compile Include="Views\Collections\_ItemsView\ItemsView.fs" />
    <Compile Include="Views\Collections\_ItemsView\ItemsView.Component.fs" />
    <Compile Include="Views\Collections\_ItemsView\ItemsView.Mvu.fs" />
    <Compile Include="Views\Collections\_ItemsViewOfCell.fs" />
    <Compile Include="Views\Collections\ListView\ListView.fs" />
    <Compile Include="Views\Collections\ListView\ListView.Component.fs" />
    <Compile Include="Views\Collections\ListView\ListView.Mvu.fs" />
    <Compile Include="Views\Collections\CollectionView\CollectionView.fs" />
    <Compile Include="Views\Collections\CollectionView\CollectionView.Component.fs" />
    <Compile Include="Views\Collections\CollectionView\CollectionView.Mvu.fs" />
    <Compile Include="Views\Collections\CarouselView.fs" />
    <Compile Include="Views\Window\Window.fs" />
    <Compile Include="Views\Window\Window.Component.fs" />
    <Compile Include="Views\Window\Window.Mvu.fs" />
    <Compile Include="Views\Application\Application.fs" />
    <Compile Include="Views\Application\Application.Component.fs" />
    <Compile Include="Views\Application\Application.Mvu.fs" />
    <Compile Include="Views\Any.fs" />
    <Compile Include="Views\_Semantics.fs" />
    <Compile Include="Component.fs" />
    <Compile Include="Program.fs" />
    <Compile Include="Async.fs" />
    <Compile Include="Environment.fs" />
    <Compile Include="AppHostBuilderExtensions.fs" />
    <Compile Include="Style.fs" />
  </ItemGroup>
  <ItemGroup>
    <!--
      FSharp.Core is fixed to a specific version that is not necessarily the latest one.
      This version will be used as the lower bound in the NuGet package
    -->
    <PackageReference Include="FSharp.Core" VersionOverride="9.0.100" PrivateAssets="All" />
    <PackageReference Include="Fabulous" Condition="'$(UseLocalProjectReference)' != 'true'" VersionOverride="3.0.0-pre21" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Maui.Controls" VersionOverride="9.0.0" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" VersionOverride="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Condition="'$(UseLocalProjectReference)' == 'true'" Include="..\..\..\Fabulous\src\Fabulous\Fabulous.fsproj" />
  </ItemGroup>
</Project>
